# Generated by Django 5.2.5 on 2025-10-02 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1024, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FormulaMass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "formula",
                    models.CharField(max_length=1024, verbose_name="Formula [M+H]"),
                ),
                ("mass", models.CharField(verbose_name="m/z")),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("value", models.CharField(max_length=1024, verbose_name="Value")),
            ],
            options={
                "ordering": ["value"],
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1024, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExcelUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="excel_uploads/", verbose_name="Excel File"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "records_imported",
                    models.IntegerField(default=0, verbose_name="Records Imported"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "clear_existing_data",
                    models.BooleanField(
                        default=False,
                        help_text="Clear all existing data before importing",
                        verbose_name="Clear Existing Data",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Subclass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1024, unique=True, verbose_name="Name"),
                ),
                (
                    "clas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.class",
                        verbose_name="Class",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Compound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("type", models.CharField(max_length=8, verbose_name="Type")),
                ("mode", models.BooleanField(verbose_name="Mode")),
                ("name", models.CharField(max_length=1024, verbose_name="Name")),
                (
                    "neutral_formula",
                    models.CharField(max_length=1024, verbose_name="Neutral Formula"),
                ),
                ("mz_ion", models.CharField(max_length=1024, verbose_name="m/z Ion")),
                ("smile", models.CharField(max_length=1024, verbose_name="SMILE")),
                (
                    "molecule_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="molecules/",
                        verbose_name="Molecule Image",
                    ),
                ),
                (
                    "clas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.class",
                        verbose_name="Class",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.compound",
                        verbose_name="Origin",
                    ),
                ),
                ("formulas", models.ManyToManyField(to="core.formulamass")),
                ("references", models.ManyToManyField(to="core.reference")),
                (
                    "subclass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subclass",
                        verbose_name="Subclass",
                    ),
                ),
                ("treatment", models.ManyToManyField(to="core.treatment")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
