# Generated by Django 5.2.5 on 2025-09-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compound",
            name="molecule_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="molecules/",
                verbose_name="Molecule Image",
            ),
        ),
    ]
