# Generated by Django 5.2.5 on 2025-09-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelupload",
            name="clear_existing_data",
            field=models.BooleanField(
                default=False,
                help_text="Clear all existing data before importing",
                verbose_name="Clear Existing Data",
            ),
        ),
    ]
