# Generated by Django 5.2.5 on 2025-10-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("login", "Login"),
                    ("register", "Register"),
                    ("query", "Query"),
                    ("import", "Import"),
                ],
                max_length=20,
                verbose_name="Event Type",
            ),
        ),
    ]
