# Generated by Django 5.2.5 on 2025-10-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_userevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="compound",
            name="notes",
            field=models.CharField(max_length=2048, null=True, verbose_name="Notes"),
        ),
    ]
