# Generated by Django 6.1.1 on 2026-10-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_excelupload_keep_on_user_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelupload',
            name='former_user_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Former user email'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='former_user_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Former user name'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='former_user_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Former user email'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='former_user_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Former user name'),
        ),
    ]
