# Generated by Django 6.1.1 on 2026-10-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_keep_deleted_user_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclass',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='subclass',
            constraint=models.UniqueConstraint(fields=('clas', 'name'), name='unique_subclass_per_class'),
        ),
    ]
