# Generated by Django 5.2.5 on 2026-10-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subclass_unique_per_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024, verbose_name='Alias')),
            ],
            options={
                'verbose_name_plural': 'class aliases',
            },
        ),
        migrations.CreateModel(
            name='SubclassAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024, verbose_name='Alias')),
            ],
            options={
                'verbose_name_plural': 'subclass aliases',
            },
        ),
        migrations.CreateModel(
            name='TreatmentAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024, verbose_name='Alias')),
            ],
            options={
                'verbose_name_plural': 'treatment aliases',
            },
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name_plural': 'classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='key',
            field=models.CharField(default='', editable=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='report',
            field=models.JSONField(blank=True, help_text='New names created by this import and any that look like existing ones', null=True, verbose_name='Import report'),
        ),
        migrations.AddField(
            model_name='subclass',
            name='key',
            field=models.CharField(default='', editable=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='treatment',
            name='key',
            field=models.CharField(default='', editable=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='classalias',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.class'),
        ),
        migrations.AddField(
            model_name='subclassalias',
            name='clas',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.class'),
        ),
        migrations.AddField(
            model_name='subclassalias',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.subclass'),
        ),
        migrations.AddField(
            model_name='treatmentalias',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.treatment'),
        ),
        migrations.AddConstraint(
            model_name='classalias',
            constraint=models.UniqueConstraint(fields=('key',), name='unique_class_alias'),
        ),
        migrations.AddConstraint(
            model_name='subclassalias',
            constraint=models.UniqueConstraint(fields=('clas', 'key'), name='unique_subclass_alias'),
        ),
        migrations.AddConstraint(
            model_name='treatmentalias',
            constraint=models.UniqueConstraint(fields=('key',), name='unique_treatment_alias'),
        ),
    ]
